"""initial_schema"""

from alembic import op
import sqlalchemy as sa

revision = "f7d40bfc5f71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "DISPATCHER", "OPERATOR", name="role", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
        sa.UniqueConstraint("email", name=op.f("uq_admins_email")),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index(op.f("ix_outbox_next_attempt_at"), "outbox", ["next_attempt_at"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_name", sa.String(length=200), nullable=False),
        sa.Column("contact_phone", sa.String(length=40), nullable=False),
        sa.Column("emergency_phone", sa.String(length=40), nullable=False),
        sa.Column("max_photo_mb", sa.Integer(), nullable=False),
        sa.Column("notification_texts", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("last_name", sa.String(length=256), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("csrf_token", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], name=op.f("fk_admin_sessions_admin_id_admins")),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_admin_sessions")),
    )
    op.create_index(op.f("ix_admin_sessions_admin_id"), "admin_sessions", ["admin_id"], unique=False)
    op.create_index(op.f("ix_admin_sessions_expires_at"), "admin_sessions", ["expires_at"], unique=False)
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_number", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("personal_account", sa.String(length=30), nullable=False),
        sa.Column(
            "application_type",
            sa.Enum(
                "METER_NOT_WORKING",
                "MPI_REMOVAL",
                "GAS_LEAK",
                name="applicationtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "IN_PROGRESS", "COMPLETED", "REJECTED", name="status", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("NORMAL", "HIGH", "CRITICAL", name="priority", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("requested_date", sa.Date(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(application_type = 'MPI_REMOVAL' AND requested_date IS NOT NULL) OR (application_type != 'MPI_REMOVAL' AND latitude IS NOT NULL AND longitude IS NOT NULL)",
            name=op.f("ck_applications_required_fields"),
        ),
        sa.CheckConstraint(
            "application_type != 'GAS_LEAK' OR priority = 'CRITICAL'", name=op.f("ck_applications_critical_gas")
        ),
        sa.CheckConstraint("latitude IS NULL OR latitude BETWEEN -90 AND 90", name=op.f("ck_applications_latitude")),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name=op.f("ck_applications_longitude")
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["admins.id"], name=op.f("fk_applications_assigned_to_admins")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_applications_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("application_number", name=op.f("uq_applications_application_number")),
        sa.UniqueConstraint("user_id", "idempotency_key", name=op.f("uq_applications_user_id")),
    )
    op.create_index(op.f("ix_applications_application_type"), "applications", ["application_type"], unique=False)
    op.create_index(op.f("ix_applications_assigned_to"), "applications", ["assigned_to"], unique=False)
    op.create_index(op.f("ix_applications_personal_account"), "applications", ["personal_account"], unique=False)
    op.create_index("ix_applications_priority_created", "applications", ["priority", "created_at"], unique=False)
    op.create_index("ix_applications_status_created", "applications", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], name=op.f("fk_audit_logs_admin_id_admins")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "application_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("owner_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "METER_PHOTO", "GAS_LEAK_PHOTO", "OTHER", name="filetype", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("telegram_file_id", sa.String(length=512), nullable=False),
        sa.Column("storage_url", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_application_files_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_files")),
        sa.UniqueConstraint("storage_url", name=op.f("uq_application_files_storage_url")),
    )
    op.create_index(op.f("ix_application_files_application_id"), "application_files", ["application_id"], unique=False)
    op.create_index(op.f("ix_application_files_created_at"), "application_files", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_application_files_owner_telegram_id"), "application_files", ["owner_telegram_id"], unique=False
    )
    op.create_table(
        "application_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column(
            "old_status",
            sa.Enum(
                "NEW",
                "IN_PROGRESS",
                "COMPLETED",
                "REJECTED",
                name="old_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "NEW",
                "IN_PROGRESS",
                "COMPLETED",
                "REJECTED",
                name="new_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("public_comment", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], name=op.f("fk_application_history_admin_id_admins")),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_application_history_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_history")),
    )
    op.create_index(
        op.f("ix_application_history_application_id"), "application_history", ["application_id"], unique=False
    )
    op.create_table(
        "realtime_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_realtime_events_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_realtime_events")),
    )
    op.create_index(op.f("ix_realtime_events_application_id"), "realtime_events", ["application_id"], unique=False)
    op.bulk_insert(
        sa.table(
            "system_settings",
            sa.column("id", sa.Integer()),
            sa.column("organization_name", sa.String()),
            sa.column("contact_phone", sa.String()),
            sa.column("emergency_phone", sa.String()),
            sa.column("max_photo_mb", sa.Integer()),
            sa.column("notification_texts", sa.JSON()),
        ),
        [
            {
                "id": 1,
                "organization_name": "Qala Gas",
                "contact_phone": "",
                "emergency_phone": "",
                "max_photo_mb": 10,
                "notification_texts": {
                    "IN_PROGRESS": "🟡 {number} өтініміңіз өңдеуге алынды.",
                    "COMPLETED": "✅ {number} өтініміңіз орындалды.",
                    "REJECTED": "❌ {number} өтініміңіз қабылданбады.",
                },
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_realtime_events_application_id"), table_name="realtime_events")
    op.drop_table("realtime_events")
    op.drop_index(op.f("ix_application_history_application_id"), table_name="application_history")
    op.drop_table("application_history")
    op.drop_index(op.f("ix_application_files_owner_telegram_id"), table_name="application_files")
    op.drop_index(op.f("ix_application_files_created_at"), table_name="application_files")
    op.drop_index(op.f("ix_application_files_application_id"), table_name="application_files")
    op.drop_table("application_files")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index("ix_applications_status_created", table_name="applications")
    op.drop_index("ix_applications_priority_created", table_name="applications")
    op.drop_index(op.f("ix_applications_personal_account"), table_name="applications")
    op.drop_index(op.f("ix_applications_assigned_to"), table_name="applications")
    op.drop_index(op.f("ix_applications_application_type"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_admin_sessions_expires_at"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_admin_id"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_outbox_next_attempt_at"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("admins")
    # ### end Alembic commands ###
